name: gecco-comp
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.10.8=h5b45459_0
  - libffi=3.4.2=h8ffe710_5
  - libzlib=1.2.11=h8ffe710_1014
  - openssl=3.0.2=h8ffe710_1
  - pip=22.0.4=pyhd8ed1ab_0
  - python=3.9.12=hcf16a7b_1_cpython
  - python_abi=3.9=2_cp39
  - setuptools=62.1.0=py39hcbf5309_0
  - sqlite=3.38.2=h8ffe710_0
  - tk=8.6.12=h8ffe710_0
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
  - pip:
    - geneticengine==0.0.8
    - lark==1.1.2
    - z3-solver==4.8.15.0
prefix: C:\Users\leoni\anaconda3\envs\gecco-comp
