name: gecco-comp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - python_abi=3.9
  - setuptools=62.1.0
  - pip=22.0.4
  - pip:
    - geneticengine==0.0.15
    - lark==1.1.2
    - z3-solver==4.8.15.0