name: srbench
channels:
    - conda-forge
dependencies:
    - make
    - compilers
    - python
    - cmake=3.19.1 # operon, feat
    - eigen=3.3.9 # operon, feat, ellyn
    - boost=1.74.0 # gpgomea, ellyn
    - pkg-config # gpgomea
    - scikit-learn=0.24.1 
    - pyarrow
    - pandas 
    - numpy
    - xgboost
    - lightgbm
    - gplearn
    - armadillo=9.900.4 # gpgomea
    - jupyter
    - pytest
    - matplotlib
    # operon 
    - pybind11=2.6.1 
    - fmt=7.1.3 
    - taskflow=3.3.0
    - xxhash
    #deep-symbolic-regression 
    - tensorflow=1.14 
    - cython
    - numba
    - sympy
    - click
    - mpi4py
    - dataclasses
    # itea
    # - libblas=3.9.0=8_openblas 
    # - liblapack=3.9.0=8_openblas
    # - gmp=6.2.1=h58526e2_0
    # - gsl=2.6=he838d99_2
    # - libffi=3.3=h58526e2_2
    # feat
    - cython=0.29.*
    - ninja
    - setuptools=45.*
    - shogun-cpp=6.1.4
    - wheel=0.35.*
    # pip
    - pip=20.3.3 
    - pip:
        # Note that PySR has a conda-forge package,
        # but it is not compatible with Apple Silicon or Windows,
        # whereas this one is.
        - pysr==0.16
        - DistanceClassifier==0.0.8 # ellyn
        - pmlb==1.0.1.post3
        - ffx==2.0.2 # ffx
        - eigency==1.77
        # BSR
        - git+https://github.com/lacava/MCMC-SymReg
        # AI-feynman
        - git+https://github.com/lacava/AI-Feynman
