name: srcomp
channels:
    - conda-forge
dependencies:
    - python
    - scikit-learn=0.24.1 
    - pandas 
    - numpy
    - jupyter
    - pytest
    - matplotlib
    - sympy
    # pip
    - pip=20.3.3 
    - pip:
        - pmlb==1.0.1.post3
        - pytest-order
