name: srbench
channels:
  - conda-forge
dependencies:
  - python
  - scikit-learn 
  - pandas 
  - numpy
  - jupyter
  - pytest
  - matplotlib
  - sympy
  - ipdb
  - seaborn
  - pyyaml
  - pip 
  - pip:
    - pmlb==1.0.1.post3
    - pytest-order
