name: Bingo
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.*
    - cmake>=3.18
    - ninja
    - eigen>=3.3
    - cython=0.29.*
    - pandas=1.1.*
    - setuptools
    - shogun-cpp=6.1.4
    - wheel=0.35.*
    - numpy>=1.14.3
    - sympy
    - pip
    - pip:
        - eigency==1.77
        - pmlb==1.*
        - mpi4py>=2.0.0,<4.0
        - numpy>=1.14.3
        - scipy>=1.6.2
        - dill>=0.2.9
        - smcpy>=0.1.4
