name: E2ET
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.8=ha878542_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_15
  - libgomp=11.2.0=h1d223b6_15
  - libnsl=2.0.0=h7f98852_0
  - libstdcxx-ng=11.2.0=he4da1e4_15
  - libzlib=1.2.11=h166bdaf_1014
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.2=h166bdaf_1
  - pip=22.0.4=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=2_cp37m
  - readline=8.1=h46c0cb4_0
  - setuptools=62.0.0=py37h89c1867_0
  - sqlite=3.37.1=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - pip:
    - args==0.1.0
    - attrs==21.4.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - clint==0.5.1
    - coverage==6.3.2
    - cycler==0.11.0
    - fonttools==4.31.2
    - functorch==0.1.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - iniconfig==1.1.1
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - mamba==0.11.2
    - matplotlib==3.5.1
    - mpmath==1.2.1
    - numexpr==2.8.1
    - numpy==1.21.5
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.1.0
    - pluggy==1.0.0
    - py==1.11.0
    - pyparsing==3.0.7
    - pytest==7.1.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - six==1.16.0
    - sympy==1.10.1
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - zipp==3.8.0
prefix: /private/home/pakamienny/anaconda3/envs/opensource
