channels:
    - conda-forge
dependencies:
    - python=3.10
    - cmake>3.3
    - gcc
    - gxx
    - ninja
    - eigen
    - pandas
    - scikit-learn
    - setuptools
    - shogun-cpp
    - wheel
    - pybind11
    - nlohmann_json
    - pybind11_json
    - pip
    - pip:
        - pmlb