name: gpg
channels:
  - conda-forge
  - nodefaults
dependencies:
  - make
  - cmake=3
  - python=3.11
  - eigen=3.4.0
  - python-devtools=0.9.0
  - pybind11
  - pip
  - pip:
    - numpy
    - scikit-learn
    - sympy
    - pandas
    - setuptools
    - torch
    - functorch
    - sympytorch
    - stopit
