name: srcomp-operon
channels:
    - conda-forge
    - anaconda
dependencies:
    - cmake>=3.20
    - eigen>=3.4.0
    - fmt=7.1.3
    - gcc=11.2.0
    - gcc_impl_linux-64=11.2.0
    - gcc_impl_linux-64=11.2.0
    - gxx=11.2.0
    - optuna
    - pip
    - pkg-config
    - pybind11
    - pytest
    - python
    - scikit-learn
    - sympy
    - taskflow=3.3.0
    - xxhash
    - pip:
        - pmlb==1.0.1.post3
